TrainingManagementSystem/Controllers/BatchController.cs
using System.Net.Http.Headers;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TMS_Application.Models;
using TMS_Application.ViewModel;

namespace TMS_Application.Controllers
{
    public class BatchController : Controller
    {
        HttpClient client = new HttpClient();
        static List<Batch> batch = null;
        static List<CourseViewModel> courseView = null;
        private void SetViewBag() => ViewBag.UserRole = HttpContext.Session.GetString("roleName");
        public BatchController()
        {
            client.BaseAddress = new Uri("https://localhost:7206/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }
       
        public async Task<ActionResult> Index()
        {
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

            List<BatchViewModel> batches = null;
            HttpResponseMessage response = await client.GetAsync("api/Batch");
            if (response.IsSuccessStatusCode)
            {
                SetViewBag();
                var jsonString = response.Content.ReadAsStringAsync();
                jsonString.Wait();
                batches = JsonConvert.DeserializeObject<List<BatchViewModel>>(jsonString.Result);
                if (batches.Count == 0)
                {
                    ViewBag.msg = "No batch exists!!!";
                    return View();
                }
                else
                {
                    return View(batches);
                }
            }
            else
            {
                ViewBag.msg = response.ReasonPhrase;
                return View();
            }
        }

        public async Task<ActionResult> ViewAvailableBatches()
        {
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
            List<BatchViewModel> batches = null;
            HttpResponseMessage response = await client.GetAsync("api/Batch/GetAvailableBatches");
            if (response.IsSuccessStatusCode)
            {
                SetViewBag();
                var jsonString = response.Content.ReadAsStringAsync();
                jsonString.Wait();
                batches = JsonConvert.DeserializeObject<List<BatchViewModel>>(jsonString.Result);
                if (batches.Count == 0)
                {
                    ViewBag.msg = "No batch exists!!!";
                    return View();
                }
                else
                {
                    return View(batches);
                }
            }
            else
            {
                ViewBag.msg = response.ReasonPhrase;
                return View();
            }
        }

        public async Task<ActionResult> Details(int id)
        {
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

            HttpResponseMessage response = await client.GetAsync("api/Batch/" + id);
            if (response.IsSuccessStatusCode)
            {
                SetViewBag();
                var jsonString = response.Content.ReadAsStringAsync();
                jsonString.Wait();
                var batch = JsonConvert.DeserializeObject<BatchViewModel>(jsonString.Result);

                if (batch == null)
                {
                    ViewBag.msg = "No Such data exists";
                    return View();
                }
                else
                {
                    return View(batch);
                }
            }
            else
            {
                ViewBag.msg = response.ReasonPhrase;
                return View();
            }
        }
        
        public async Task<ActionResult> Create()
        {
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

            HttpResponseMessage response = await client.GetAsync("api/Batch/GetCourseNames");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = response.Content.ReadAsStringAsync();
                jsonString.Wait();
                courseView = JsonConvert.DeserializeObject<List<CourseViewModel>>(jsonString.Result);
            }
            if (courseView == null || !courseView.Any())
            {
                ViewBag.Msg = "No courses available";
            }

            ViewBag.courses = new SelectList(courseView, "CourseId", "CourseName");

            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Batch batch)
        {
            batch.CreatedBy = Convert.ToInt32(HttpContext.Session.GetString("userId"));
            batch.CreatedOn = DateTime.Now;
            batch.BatchId ??= 0;

            try
            {
                client.DefaultRequestHeaders.Authorization =
               new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

                StringContent content = new StringContent
                    (JsonConvert.SerializeObject(batch), Encoding.UTF8, "application/json");
                var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                client.DefaultRequestHeaders.Accept.Add(contentType);
                HttpResponseMessage response = await client.PostAsync("api/Batch", content);

                if (response.IsSuccessStatusCode)
                {
                    var jsonString = response.Content.ReadAsStringAsync();
                    jsonString.Wait();
                    var temp = JsonConvert.DeserializeObject<Batch>(jsonString.Result);
                    if (temp != null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.msg = "Some error occured!! Try later";
                        return View();
                    }
                }
                else
                {
                    var errorMessage = await response.Content.ReadAsStringAsync();
                    ViewBag.msg = "Error: " + response.StatusCode + " - " + errorMessage;
                    return View(batch);
                    //ViewBag.msg = response.ReasonPhrase;
                    //return View();
                }
            }
            catch
            {
                return View();
            }

        }
       
        public async Task<ActionResult> Edit(int id)
        {
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

            HttpResponseMessage response = await client.GetAsync("api/Batch/GetCourseNames");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = response.Content.ReadAsStringAsync();
                jsonString.Wait();
                courseView = JsonConvert.DeserializeObject<List<CourseViewModel>>(jsonString.Result);
            }
            if (courseView == null || !courseView.Any())
            {
                ViewBag.Msg = "No courses available";
            }

            ViewBag.courses = new SelectList(courseView, "CourseId", "CourseName");

            HttpResponseMessage response1 = await client.GetAsync("api/Batch/" + id);
            if (response1.IsSuccessStatusCode)
            {
                var jsonString = response1.Content.ReadAsStringAsync();
                jsonString.Wait();
                var batch = JsonConvert.DeserializeObject<Batch>(jsonString.Result);

                return View(batch);
            }
            else
            {
                ViewBag.msg = response1.ReasonPhrase;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Batch batch)
        {
            batch.Updated = DateTime.Now;
            batch.UpdatedBy = Convert.ToInt32(HttpContext.Session.GetString("userId"));
            batch.BatchId ??= 0;

            try
            {
                client.DefaultRequestHeaders.Authorization =
               new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

                StringContent content = new StringContent
                    (JsonConvert.SerializeObject(batch), Encoding.UTF8, "application/json");
                var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                client.DefaultRequestHeaders.Accept.Add(contentType);
                HttpResponseMessage response = await client.PutAsync("api/Batch/" + id, content);
                if (response.IsSuccessStatusCode)
                {
                    var jsonString = response.Content.ReadAsStringAsync();
                    jsonString.Wait();
                    var temp = JsonConvert.DeserializeObject<Batch>(jsonString.Result);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.msg = response.ReasonPhrase;
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
                
        public async Task<ActionResult> Delete(int id)
        {
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

TrainingManagementSystem/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
	<link rel="stylesheet" href="~/css/login.css">
	<link rel="stylesheet" href="~/js/login.js">
</head>
<body>
   
        <section class="container">
            <div class="login-container">
                <div class="circle circle-one"></div>
                <div class="form-container">
                    <img src="https://raw.githubusercontent.com/hicodersofficial/glassmorphism-login-form/master/assets/illustration.png" alt="illustration" class="illustration" />
                    <h1 class="opacity">LOGIN</h1>
                    <form>
                        <input type="text" placeholder="USERNAME" />
                        <input type="password" placeholder="PASSWORD" />
                        <button class="opacity">SUBMIT</button>
                    </form>                    
                </div>
                <div class="circle circle-two"></div>
            </div>
            <div class="theme-btn-container"></div>
        </section>
    
    <div>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

TrainingManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Training_Management_System</title>

    <!-- Bootstrap CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <!-- jQuery (required for Bootstrap's JavaScript plugins) -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Bootstrap JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>
        body {
        background-color: #f8f9fa; /* Light gray background */
        }

        .navbar {
        background-color: #FAD2D2; /* Bootstrap primary color */
        }

        .navbar-brand, .nav-link {
        color: #000000 !important;
        margin-right: auto;
        }

        .navbar-toggler-icon {
        background-color: #ffffff;
        }

        .text-box {
        text-align: center;
        margin: 20px 0;
        }

        .footer {
        background-color: #343a40; /* Dark footer */
        color: #ffffff;
        padding: 15px 0;
        text-align: center;
        }
    </style>
</head>
<body>

    <header>
        <!-- Navbar -->
        @if (ViewBag.HideHeader == null || !ViewBag.HideHeader)
        {



            <nav class="navbar navbar-expand-sm navbar-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">ABC Training Institution</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse" id="navBarCollapse">
                        <ul class="navbar-nav">
                            @if (ViewBag.UserRole != "User")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Course Details</a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdown1">
                                        <li class="dropdown-item active">
                                            <a class="nav-link" asp-area="" asp-controller="Course" asp-action="Index">View all Courses</a>
                                        </li>                                  
                                        <li class="dropdown-item">
                                            <a class="nav-link" asp-area="" asp-controller="Course" asp-action="Create">Create new Course</a>
                                        </li>
                                    </ul>                                
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="dropdown2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Batch</a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdown2">

                                        <li class="dropdown-item">
                                            <a class="nav-link" asp-area="" asp-controller="Batch" asp-action="Index">View all Batches</a>
                                        </li>                                    
                                        <li class="dropdown-item">
                                            <a class="nav-link" asp-area="" asp-controller="Batch" asp-action="Create">Create new Batch</a>
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link" asp-area="" asp-controller="Enrollment" asp-action="Index">View enrollments for the batch</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="dropdown3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">User</a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdown3">
                                        <li class="dropdown-item">
                                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">View all Users</a>
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Create">Create new User</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                            else{
                                <li class="nav-item active">
                                    <a class="nav-link" asp-area="" asp-controller="Course" asp-action="ViewAvailableCourses">View Available Courses</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Batch" asp-action="ViewAvailableBatches">View Available Batches</a>
                                </li>
                            }
                        </ul>
                            
                            <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <p class="nav-link fw-bolder">Welcome <span>@ViewBag.User&nbsp;</span></p>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>
        }
    </header>

    <main role="main" class="container">
        <div class="jumbotron text-center">
            @RenderBody()
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            &copy; 2024 - Training_Management_System - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-light">Privacy</a>
        </div>
    </footer>
        <!-- Scripts -->

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> 